server:
  port: 8080
  address: 0.0.0.0
  servlet:
    context-path: /eis

spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://192.168.100.210:1433;databaseName=MEDIPLUS_DEV;encrypt=false;sendStringParametersAsUnicode=false;packetSize=4096;
    username: mccsi
    password: mccsi_3574

mybatis:
  configuration:
    default-statement-timeout: 180 # 10초 동안 DB 응답 없으면 강제 에러 발생!
